Introduction to Generating Matrices for Dataset Creation

In [145]:
#generate a large list representing x,y,z values for systems of equations.
import numpy as np
multiplier = np.random.randint(25,60)
multiplier = multiplier *3
#print(multiplier)
xyz_lst = np.random.randint(0,21,multiplier) #make this into sets of 3

#splitting list into xzy chunks https://www.geeksforgeeks.org/python/how-to-split-lists-in-python/
# Number of Sets
n = 3

    # Splitting Sets and Storing them in List
xyz_sys = [xyz_lst.tolist()[i:i + n] for i in range(0, len(xyz_lst), n)]



In [146]:
print(xyz_sys[0:6])

[[14, 12, 4], [1, 12, 0], [1, 4, 7], [10, 0, 12], [8, 0, 13], [19, 3, 3]]


In [147]:
#should be divisible by 3 considering index
print(int((len(xyz_sys)-1)/3))

17


In [148]:
#matrix A
A = []
n = int((len(xyz_sys)-1)/3)
for i in range(n):
   A.append(xyz_sys[i])

A = np.array(A)

print(A)


[[14 12  4]
 [ 1 12  0]
 [ 1  4  7]
 [10  0 12]
 [ 8  0 13]
 [19  3  3]
 [11 11 11]
 [ 2 14 15]
 [ 1 14  8]
 [18 11  3]
 [20  9  7]
 [10 17  9]
 [15  4 12]
 [18 12  0]
 [ 8 13 18]
 [ 4 18  7]
 [ 0  4 15]]


In [ ]:
#put it altogether

def create_matrix(num_range):
    """
    user inputs number range for x,y,z values
    create list of size generated as a random number, converted into x, y, z 
    and transformed into array.
    """
    multiplier = np.random.randint(15,25)
    multiplier = multiplier *3
    xyz_lst = np.random.randint(0,num_range,multiplier) #make this into sets of 3
    n = 3

#splitting list into xzy chunks https://www.geeksforgeeks.org/python/how-to-split-lists-in-python/
# Number of Sets
# Splitting Sets and Storing them in List
    xyz_sys = [xyz_lst.tolist()[i:i + n] for i in range(0, len(xyz_lst), n)]
    matrix = []
    n_lst = int(len(xyz_sys))
    for i in range(n_lst):
        matrix.append(xyz_sys[i])
    
    matrix = np.array(matrix)
    return(matrix)

In [144]:
create_matrix(50)

array([[ 0, 11,  4],
       [11, 46,  6],
       [48,  5, 22],
       [11, 43, 46],
       [48,  1, 26],
       [ 9, 45, 22],
       [29, 14, 41],
       [37, 29,  3],
       [31, 49, 47],
       [10, 41, 35],
       [ 0, 13, 36],
       [46,  8, 21],
       [33, 40, 36],
       [22,  9, 27],
       [18, 43, 49],
       [35, 30, 15],
       [ 2, 44,  1],
       [44, 34, 33],
       [38, 15, 20]])